version: '3'

services:
  frontend:
    build: frontend/.
    ports:
      - 4200:80
    network_mode: bridge

    # Link this container to the postgres container with hostname 'postgres'
    external_links:
      - node:node
    
volumes:
  postgres_data: