apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-krankenhaus
  name: ms-krankenhaus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-krankenhaus
    spec:
      containers:
      - image: ms-krankenhaus-frontend
        name: ms-krankenhaus-frontend
        ports:
        - containerPort: 80
      - image: ms-krankenhaus-backend
        name: ms-krankenhaus-backend
        ports:
        - containerPort: 8080
        - containerPort: 50051
      restartPolicy: Always
status: {}