apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-krankenhaus
  name: ms-krankenhaus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-krankenhaus
    spec:
      containers:
      - image: ms-krankenhaus-frontend
        name: ms-krankenhaus-frontend
        ports:
        - containerPort: 80
      - image: ms-krankenhaus-backend
        name: ms-krankenhaus-backend
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080
      - image: postgres
        name: ms-krankenhaus-db
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-krankenhaus
                key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: db
          subPath: krankenhaus-db
      restartPolicy: Always
      volumes:
      - name: db
        gcePersistentDisk:
          pdName: ms-krankenhaus
          fsType: ext4
status: {}