version: '3'

services:
  backend:
    build: backend/.
    ports:
      - 8080:8080
      - 50051:50051
    depends_on:
      - db   
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: krankenhaus
      POSTGRES_PASSWORD: sgse-ss2020
      POSTGRES_DB: krankenhaus
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: