version: '3'

services:
  frontend:
    build: client/.
    ports:
      - 4200:80

  backend:
    build: server/.
    ports:

      - 8081:8081

      - 50051:50051

    depends_on:
      - db   

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: krankenhaus
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: krankenhaus
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: