# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_pb2 as user__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/user.UserService/GetUser',
        request_serializer=user__pb2.GetPayload.SerializeToString,
        response_deserializer=user__pb2.User.FromString,
        )
    self.ListUsers = channel.unary_stream(
        '/user.UserService/ListUsers',
        request_serializer=user__pb2.Empty.SerializeToString,
        response_deserializer=user__pb2.User.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__pb2.GetPayload.FromString,
          response_serializer=user__pb2.User.SerializeToString,
      ),
      'ListUsers': grpc.unary_stream_rpc_method_handler(
          servicer.ListUsers,
          request_deserializer=user__pb2.Empty.FromString,
          response_serializer=user__pb2.User.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
